name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  phpunit-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install PHP Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Create App Key
      run: php artisan key:generate
    - name: Install Node dependencies
      run: npm install
    - name: Execute tests via PHPUnit
      run: vendor/bin/phpunit
